version: latest

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "5000:5000"


  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "3000:4000"
