version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build

  test:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: ./node_modules/.bin/mocha dist/tests/*.test.js
      - store_test_results:
          path: ~/project/test-results
          destination: test-results

  store_test_results:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - store_test_results:
          path: ~/project/test-results
          destination: test-results

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - store_test_results:
          requires:
            - test
