version: 2.1

executors:
  node-docker:
    docker:
      - image: rwigara/e-commerce-lydia-32-bn-backend:latest

jobs:
  build:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
  dockers:
    executor: node-docker
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Push application Docker image
          command: |
            docker login -e rodrirwigara@gmail.com -u rwigara -p 49jRxLG2vqj7D6%
            docker tag dockerapp_dockerapp rwigara/rwigara/e-commerce-lydia-32-bn-backend:latest
            docker push rwigara/e-commerce-lydia-32-bn-backend:latest

  store_test_results:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - store_test_results:
          path: ~/project/test-results  # Ensure this path matches your test results directory
          destination: test-results
      
            

workflows:
  build_and_deploy:
    jobs:
      - build
      - store_test_results:
          requires:
            - build
      - dockers    
     
             
