version: 2.1

executors:
  node-docker:
    docker:
      - image: rwigara/e-commerce-lydia-32-bn-backend:latest
    

jobs:
  build:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build

  dockers-install:
    executor: node-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.25.0'
          command: |
            apk update && apk upgrade && apk add curl
            curl -sSL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            mkdir -p ~/.docker/cli-plugins
            chmod +x ~/docker-compose
            mv ~/docker-compose ~/.docker/cli-plugins/docker-compose
           
           
  docker-build-and-push: 
    executor: node-docker
    steps:
      - checkout
      - setup_remote_docker    
      - run:
          name: Run tests and push Docker image
          command: |
            docker-compose build
            docker login -u $DOCKERUSERNAME -p $DOCKERHUB_PASSWORD
            docker tag rwigara/e-commerce-lydia-32-bn-backend:latest rwigara/e-commerce-lydia-32-bn-backend:latest
            docker push rwigara/e-commerce-lydia-32-bn-backend:latest

  store_test_results:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - store_test_results:
          path: ~/project/test-results  # Ensure this path matches your test results directory
          destination: test-results

workflows:
  build_and_deploy:
    jobs:
      - build
      - store_test_results:
          requires:
            - build
      - dockers-install:
          requires:
            - build
      - docker-build-and-push:
          requires:
            - build
            - dockers-install

            
