version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile TypeScript
          command: yarn run build
      - store_artifacts:
          path: dist

  test:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile TypeScript
          command: yarn run build
      - run:
          name: Run Tests
          command: yarn test
      - store_test_results:
          path: ~/project/test-results
          destination: test-results
      - store_artifacts:
          path: dist/tests

  coverage:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile TypeScript
          command: yarn run build
      - run:
          name: Run Coverage
          command: yarn coverage
      - persist_to_workspace:
          root: .
          paths:
            - coverage

  coveralls:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Compile TypeScript
          command: yarn run build
      - run:
          name: Install Coveralls
          command: yarn global add coveralls@latest
      - run:
          name: Upload Coverage to Coveralls
          command: yarn coveralls

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - coveralls:
          requires:
            - coverage