version: 2.1

executors:
  node-docker:
    docker:
      - image: rwigara/e-commerce-lydia-32-bn-backend:latest

jobs:
  build:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build

  install_docker:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="20.10.7"  # Consider using a more recent version
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

  docker_build_and_push:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            TAG="${CIRCLE_BUILD_NUM}"
            docker build -t rwigara/e-commerce-lydia-32-bn-backend:$TAG .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push rwigara/e-commerce-lydia-32-bn-backend:$TAG

  store_test_results:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - store_test_results:
          path: ~/project/test-results  # Ensure this path matches your test results directory
          destination: test-results

workflows:
  build_and_deploy:
    jobs:
      - build
      - store_test_results:
          requires:
            - build
      - docker_build_and_push:
          requires:
            - build
      - install_docker
             
