version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build app
          command: yarn run build 

  test:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile 
      - run:
          name: Run Tests
          command: yarn test
      - store_test_results:
          path: ~/project/test-results
          destination: test-results
      - store_artifacts:
          path: coverage 

  coverage:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile 
      - run:
          name: Run Coverage
          command: yarn coverage 
      - store_artifacts:
          path: coverage 

  upload_coverage:
    docker:
      - image: cimg/node:21.7.2-browsers
    steps:
      - checkout
      - run:
          name: Set Coveralls Token
          command: echo "COVERALLS_REPO_TOKEN=yFiUuLrLceZ1GW1pZr3RpGSHb2nSPtQsI" >> $HOME/.bashrc
      - run:
          name: Install Coveralls
          command: yarn global add coveralls
      - run:
          name: Upload Coverage
          command: yarn coveralls 

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
      - upload_coverage:
          requires:
            - coverage
