version: 2.1

executors:
  node-docker:
    docker:
      - image: cimg/node:21.7.2-browsers

jobs:
  build:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: 'Say hello'
          command: 'echo Hello, World!'
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build

  build_and_push_docker:
    docker:
      - image: circleci/docker:latest
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t your-dockerhub-username/your-image-name:latest .
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push your-dockerhub-username/your-image-name:latest

  store_test_results:
    executor: node-docker
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - store_test_results:
          path: ~/project/test-results
          destination: test-results

workflows:
  build_and_deploy:
    jobs:
      - build
      - store_test_results:
          requires:
            - build
      - build_and_push_docker:
          requires:
            - build
